config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products do
    resources :order_items
  end

  resource :cart

  get 'info', to: 'pages#info'

  root 'pages#home'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items

  def total_quantity
    @count = 0

    order_items.all.each do |item|
      @count = @count + item.quantity
    end

    @count
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product
  belongs_to :cart, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

  validates :title, presence: true
  validates :price, presence: true
  validates :description, presence: true

  mount_uploader :image_1, ProductImageUploader
  mount_uploader :image_2, ProductImageUploader
  mount_uploader :image_3, ProductImageUploader
  mount_uploader :image_4, ProductImageUploader
  mount_uploader :image_5, ProductImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_cart
  helper_method :current_cart

  def current_cart
    if session[:cart_id].present?
      @current_cart = Cart.find(session[:cart_id])
    else
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show

  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @quantity = form_params[:quantity]
    @current_cart.order_items.create(product: @product, quantity: @quantity)

    flash[:success] = "Thanks for adding to your cart"
    redirect_to product_path(@product)
  end

  def update
    @product = Product.find(params[:product_id])
    @order_item = OrderItem.find(params[:id])
    @order_item.update(form_params)

    flash[:success] = "Thanks for updating your cart"
    redirect_to product_path(@product)
  end


  def destroy
    @product = Product.find(params[:product_id])
    @order_item = OrderItem.find(params[:id])

    @order_item.delete

    flash[:success] = "Product removed from cart"

    redirect_to cart_path

  end


  def form_params
    params.require(:order_item).permit(:quantity)
  end







end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @featured = Product.where(is_featured: true)
  end

  def info

  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @order_item = @current_cart.order_items.find_by(product: @product)

    if @order_item.nil?
      @order_item = @current_cart.order_items.new(product: @product, quantity: 1)

    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<h1> cart </h1>

<% if @current_cart.order_items.any? %>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Price</th>
      <th>Quantity</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @current_cart.order_items.each do |item|%>
      <tr>
        <td> <%=item.product.title %> </td>
        <td> <%=item.product.price %> </td>
        <td> <%=item.quantity %> </td>
        <td>
          <%=link_to 'remove', product_order_item_path(item.product, item), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
  <p> There are no items in your cart </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anotherpin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to 'Another Pin Co', root_path %></h1>
      <nav>
        <%= link_to 'Shop', products_path %>
        <%= link_to 'Info', info_path %>
        <%= link_to cart_path do %>
          Cart (<%= @current_cart.total_quantity %>)
        <% end %>
      </nav>
    </header>
    <% if flash[:success].present? %>
      <div class='success'>
        <%= flash[:success]%>
      </div>
    <% end %>
    <%= yield %>
    <footer>
      <p>Copyright 2019</p>
      <p>Terms & Conditions</p>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<h1> Home Page </h1>

<h2> Featured Pins </h2>

<%= render partial: 'products/product', collection: @featured %>

app/views/pages/info.html.erb
<h1>About Another Pin Co. </h1>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eget fermentum quam, quis rutrum enim. Donec sit amet neque est. Curabitur pulvinar, turpis nec faucibus vulputate, nunc ipsum mollis mi, a fringilla quam odio et nisi. Fusce sollicitudin ex nec justo porta accumsan. Cras luctus varius placerat. </p>

app/views/products/_product.html.erb
<div class='product'>
  <%= link_to product_path(product) do%>
    <%=image_tag product.image_1.medium.url %>
  <% end %>

  <h3> <%= link_to product.title, product_path(product) %> </h3>
  <p>$10</p>
</div>

app/views/products/index.html.erb
<h1>2017 Collection</h1>

<%= render partial: 'product', collection: @products %>

app/views/products/show.html.erb
<h2> <%= @product.title %> </h2>

<p><%=simple_format @product.description %></p>

<%= simple_form_for [@product, @order_item] do |f| %>
  <%= f.input :quantity %>
  <%= f.button :submit, 'Add to Cart' %>
<% end %>

<p><%= link_to 'Back to all products', products_path %>